### ISSUE TITLE
Failed to resolve module specifier 'controllers/nested_form_controller'

### ISSUE THREAD

**Issue by SemihCag** [stimulus-components/stimulus-rails-nested-form#12]
Hi, I am using nested_form but I have a error. 

I am using rails7 and importmap (pin)

I have this error on browser console
Error
`Failed to autoload controller: nested-form TypeError: Failed to resolve module specifier 'controllers/nested_form_controller'
`

Form is working but I want to clear this error. 

Can you help me? 

Importmap.rb
`pin "stimulus-rails-nested-form", to: "https://ga.jspm.io/npm:stimulus-rails-nested-form@4.0.0/dist/stimulus-rails-nested-form.es.js"`

application.js
`import NestedForm from 'stimulus-rails-nested-form'`
`application.register('nested-form', NestedForm)`

**Comment by mirrorspock** [comment]
I have the same error in my console:
importmap.rb
```
pin "stimulus-rails-nested-form", to: "https://ga.jspm.io/npm:stimulus-rails-nested-form@4.1.0/dist/stimulus-rails-nested-form.mjs"
```

and a controllers/nested_form_controller.js
```
import { Application } from '@hotwired/stimulus'
import NestedForm from 'stimulus-rails-nested-form'
const application = Application.start()
application.register('nested-form', NestedForm)
```

it works here also, but I would like to get rid of the error.

**Comment by guillaumebriday** [comment]
Hey, reopen in the main monorepo https://github.com/stimulus-components/stimulus-components if needed! 👍
