### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by scottbarrow** [stimulus-components/stimulus-rails-nested-form#25]
https://github.com/stimulus-components/stimulus-rails-nested-form/blob/master/CHANGELOG.md#500---2024-03-23 was added March, are you able to please release this as a new version?

**Comment by arr-dev** [comment]
@scottbarrow As it says in the change log, it's moved to https://www.npmjs.com/package/@stimulus-components/rails-nested-form

**Comment by guillaumebriday** [comment]
Yeah sorry I need to finish the migration to the main monorepo for this components as well 👍 
Will do that this week probably
